server:
  port: 80
spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: restaurant-service
          uri: http://localhost:8081
          predicates:
            - Path=/restaurant/**
          filters:
            - AddRoleFilter
        - id: register
          uri: http://localhost:8080
          predicates:
            - Path=/register
          filters:
            - RewritePath=/register, /auth/register
        - id: login
          uri: http://localhost:8080
          predicates:
            - Path=/login
          filters:
            - RewritePath=/login, /auth/login
        - id: validator
          uri: http://localhost:8080
          predicates:
            - Path=/validate
          filters:
            - AuthValidationFilter
            - RewritePath=/validate, /token/validate
        - id: user-info
          uri: http://localhost:8080
          predicates:
            - Path=/user-info
          filters:
            - AuthValidationFilter
            - RewritePath=/user-info, /token/user-info
        - id: menu
          uri: http://localhost:8081
          predicates:
            - Path=/menu
          filters:
            - AuthValidationFilter
            - RewritePath=/menu, /restaurant/dish/menu